### ISSUE TITLE
Unable to upload files getting error

### ISSUE THREAD

**Issue by leelavinodh** [gautam-chawla/Codeigniter-S3-bucket-upload#1]
while I try to upload the file I am getting this error. How to fix.

I am able to list objects from my s3 bucket.

My Codeigniter version is 3 and using PHP7

**Comment by gautam-chawla** [comment]
@leelavinodh Can you describe the error?

**Comment by gautam-chawla** [comment]
@leelavinodh I have updated the library file with New functions. Please check and let me know if any help needed.
